### ISSUE TITLE
EPM does not deploy contract that is member of another previously deployed contract

### ISSUE THREAD

**Issue by SCBuergel** [eris-ltd/eris-cli#1059]
I am running Eris 0.11.4 on Ubuntu 16.04.1x64 on DO
I have two contracts:
A.sol:
```
import "B.sol";
contract A {
  B myB;
}
```
and B.sol:
```
contract B {
}
```
and the following epm.yaml:
```
jobs:

- name: deployContractA
  job:
    deploy:
      contract: contracts/A.sol
      instance: A
      wait: true

- name: deployContractB
  job:
    deploy:
      contract: contracts/B.sol
      instance: B
      wait: true
```
I am running the EPM via
```
chain_dir=$HOME/.eris/chains/mychain
addr=$(cat $chain_dir/addresses.csv | grep mychain_full_000 | cut -d ',' -f 1)
eris pkgs do --chain mychain --address $addr
```
--> this does not deploy `B` in the job `deployContractB` as evidenced by no output address in terminal and no entry in epm.json.
When removing the two lines `import "B.sol";` and `B myB;` from `A.sol` both contracts get deployed correctly.
