### ISSUE TITLE
Is there any way to retrieve the transaction hash? 

### ISSUE THREAD

**Issue by somak12** [eris-ltd/eris-cli#1140]
Not sure if this feature is available right now, if not is there any way to get the transaction hash as argument in an event. Trying to create something like https://etherchain.org/ 

block.blockhash() --> can be an option but it has some limitations. mentioned below:
block.blockhash(uint blockNumber) returns (bytes32): hash of the given block - only works for 256 most recent blocks excluding current.

**Comment by VoR0220** [comment]
Depends what you're talking about.

If you're referring to how to do this in js, I'd recommend you go to https://github.com/eris-ltd/eris-contracts.js and file an issue there.

If you're referring to how to do this in PM through a call job, then simply add the `save` key, and for the result of the key input "tx"

```
- name: someName
  job:
     call:
        source: MySource
        destination: myDestination
        function: myFunc
        data: [some,data,here]
        save: tx
```
