### ISSUE TITLE
eris pkgs do fails when using a library in a sol file (encoding/hex: invalid byte: U+005F '_')

### ISSUE THREAD

**Issue by rlaveycal** [eris-ltd/eris-cli#590]
Using eris 0.11.3 and sol file
```
library test{
    function double(uint self) constant returns (uint){
        return self * 2;
    }
}
contract TestC{
    using test for uint;
    
    function td(){
        uint x = 4;
        var y = x.double();
    }
}
```

Trying to add this to a chain fails with error (from debug mode):
```
Compiling code remotely                   url=https://compilers.eris.industries:10113/compile
Error compiling contracts
encoding/hex: invalid byte: U+005F '_'
```

The code compiles in the Solidity online compiler. 

Interestingly the bytecode for the contract (from the online compiler) is
```
606060405260c48060106000396000f360606040526000357c010000000000000000000000000000000000000000000000000000000090048063a3ffac0d146037576035565b005b604260048050506044565b005b60006000600491508173__test__________________________________63eee972069091604051827c01000000000000000000000000000000000000000000000000000000000281526004018082815260200191505060206040518083038160008760325a03f2156002575050506040518051906020015090505b505056
```

So I'm guessing what looks like the reference to the library isn't being parsed properly?

Edit: I've just found the eris-pm docs and tried changing my epm.yaml so that I deployed the library in a separate step from a file with just the library, then set the libraries: setting to that address:

```
jobs:

- name: deployUniqueString
  job:
    deploy:
      contract: UniqueString.sol
      instance: all
      wait: true

- name: deployAccounts
  job:
    deploy:
      contract: Accounts.sol
      instance: all
      libraries: test:$deployUniqueString
      wait: true

```

I get a slightly different error on the second step:
```
encoding/hex: invalid byte: U+0053 'S'
```
