### ISSUE TITLE
eris pkgs call job fails : failed to unmarshal unsupported arg slice type: bytes1[12][100]

### ISSUE THREAD

**Issue by rlaveycal** [eris-ltd/eris-cli#593]
Eris 0.11.3. 

When I try to call a function on my contract in the epm.yaml I get the error
```
failed to unmarshal unsupported arg slice type: bytes1[12][100]
```
My contract has a function that returns bytes[12][100] but I'm not calling it.

**Comment by compleatang** [comment]
Thanks for the report, but that is not much to go on. In order to look into the issue we'll need a reproducible test case.

**Comment by rlaveycal** [comment]
types.sol:
```
contract Types{
    function getPositive() constant returns (uint){
        return 13;
    }
    function getBytes() constant returns (byte[10][2]){
        byte[10][2] memory b;
        string memory s = "hello";
        bytes memory sb = bytes(s);

        uint k = 0;
        for (uint i = 0; i < sb.length; i++) b[0][k++] = sb[i];
        b[1][9] = 0xff;
        return b;
    }
}
```

epm.yaml:
```
jobs:

- name: deployStorageK
  job:
    deploy:
      contract: types.sol
      wait: true

- name: queryStorage
  job:
    query-contract:
      destination: $deployStorageK
      data: getPositive
```
Result:
```
Performing action. This can sometimes take a wee while
Executing Job                                 defaultAddr
Executing Job                                 deployStorageK
Contract Address                              39CEB12E144538E8E023BB7AC72CFFE00AA5F8D0
Transaction Hash                              D76158BA415D938C6BC0B16F21CD1C18C45EFCFE
Executing Job                                 queryStorage
ABI Error                                 abi=
                                         data=getPositive
                                         dest=39CEB12E144538E8E023BB7AC72CFFE00AA5F8D0
                                       rawErr=unsupported arg slice type: bytes1[10][2]

```
