### ISSUE TITLE
rethink how actions definitions can be used

### ISSUE THREAD

**Issue by compleatang** [eris-ltd/eris-cli#60]
**Option A** (this the current default):

* start some chains/services
* wrap a bunch of command line steps

**Option B** (wrap CLI tools for aliasing):

* focus on what a particular image "can do" to a data_container
* rely on ENTRY_POINT stuff

**Option C** (both)

----

**Option B** would require the following field additions to `actions` struct:

* data_containers = [ "srvNameA", "chainNameB" ]
* run_tool_image = "imageOfTheToolToRun"

If `run_tool_image` && `data_containers` were present in the action definition file then Option A would not be used and Option B would be used instead. How would this look?

```toml
name = "chain info"
run_tool_image = [ "eris/mintinfo" ] # this would simply be FROM eris/erisdb with ENTRY_POINT ["mintinfo"]
data_containers = [ "$HEAD" ] # assuming we may want to add a chain checkout feature

[environment]

[maintainer]
name = "Eris Industries"
email = "support@erisindustries.com"

[location]
repository = "github.com/eris-ltd/eris-actions"

[machine]
include = ["docker"]
requires = [""]
```

The above, if saved as `~/.eris/actions/chain_info.toml` would then be called using the following:

```bash
eris actions do chain info consensus
```

indeed, then @dennismckinnon could add an alias of:

```bash
alias cinf="eris actions do chain info"
```

which would be called via:

```bash
cinf consensus
```

Despite being `4` letters instead of the famous `Denny3`, I'd give such a possibility a: :fire_engine: 

----

For the record, I'd be in favor of **Option C**
