### ISSUE TITLE
deploying contract does not create `abi` folder and `epm.json`

### ISSUE THREAD

**Issue by SCBuergel** [eris-ltd/eris-cli#706]
**What I expected to happen:**
I am deploying two contracts, loosely following the tutorial section and upon `eris pkgs do --chain simplechain --address $addr` I expect to get the `abi` folder and the file `epm.json` to be written to my `.eris\apps\` subfolder.

**What actually happened:**
The `abi` folder and the file `epm.json` do not get written to disk.

**Steps to reproduce:**
This issue is hard to reproduce, the exact same code did work on my Digital Ocean machine but did not work locally. [This](https://gist.github.com/SCBuergel/1137c7324e5b37bab6031251d63a4185) is the debug output of the working version and [this](https://gist.github.com/SCBuergel/039fe0ff628331bfa99ca5cafa4ce4aa) is the version that did not write the output files and [this](https://www.diffchecker.com/xlppap6k) is the diffed version which clearly shows that both versions are exactly the same except for the addresses.

My `epm.yaml` file looks as follow:
```
jobs:

- name: deployAtmContract
  job:
    deploy:
      contract: atmContract.sol
      wait: true

- name: deployMainContract
  job:
    deploy:
      contract: contract.sol
      wait: true
```

I am using eris 0.11.4 installed as binary on Ubuntu 15.10.
```
docker version
Client:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:38:55 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.1
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   5604cbe
 Built:        Tue Apr 26 23:38:55 2016
 OS/Arch:      linux/amd64
```
